package org.kishan.year_2021.month_september.date_14;

import java.util.HashMap;
import java.util.Map;

public class MaxNumberOfBalloon {
	static int maxNumberOfBalloons(String text) {
		Map<Character,Integer> map = new HashMap<>();

		map.put('b',0);
		map.put('a',0);
		map.put('l',0);
		map.put('o',0);
		map.put('n',0);

		for(int i = 0; i<text.length();i++){
			char c = text.charAt(i);
			if(map.containsKey(c)){
				map.put(c,map.get(c)+1);
			}
		}

		int min = Math.min(map.get('b'),Math.min(map.get('a'),map.get('n')));
		if(min > 0){
			if(min == 1 && map.get('l') >= 2 && map.get('o') >= 2){
				return min;
			}
			else if(min > 1 && map.get('l') >= 2 && map.get('o') >= 2){
				int minDouble = Math.min(map.get('l'),map.get('o'));
				while((min*2) > minDouble && min > 0){
					min--;
				}
				return min;
			}
			return 0;
		}
		return min;
	}

	static int maxBalloonConstantSpace(String text){
		int bCount = 0,aCount = 0,lCount =0, oCount = 0,nCount = 0;
		for(int i = 0; i < text.length(); i++) {
			if(text.charAt(i) == 'b') bCount++;
			else if(text.charAt(i) == 'a') aCount++;
			else if(text.charAt(i) == 'l') lCount++;
			else if(text.charAt(i) == 'o') oCount++;
			else if(text.charAt(i) == 'n') nCount++;
		}

		lCount /= 2;
		oCount /= 2;

		return Math.min(bCount,Math.min(aCount,Math.min(lCount,Math.min(oCount,nCount))));
	}

	public static void main(String[] args) {
		String s = "siobnxjnmhnzoxjztwoezeqgoqkhetrpwszmwwwfpyybcizuzhrxriynbyjpbeplhfavddkwspyoddheetjgfqsmywnmxjviftexuzdbpuexfhsmyagqefhdilhehlhkitmkijgzoogicywcfxzalrvayrxavieoqodwoasbxuuuormvktvhwlidiilotsfwgcztxjktibraglhnhneororppplsylbfkebmqbzvftzsrrwfoiifajmxkjxtaxmvfmgxkdbxdycgottuymuknrnhjjcpwkpmbweirromdikbtcptxgtkslozeoejpchphkydsjexwjkiquaahuphtqftzoayqyqevtwszfmmkjqoqxexexltnwxpisszxdxljfubboxalbxhmnuabbypkpmrxyecuibqjoixdbjfvinxcgnjtwpyhieqneerorbllszkavoxearikldjeomdzyotdxioprkkvisadoccdrhkdknoyzmldomfdytzuvwvwoqatojlczydkvyfifkygtmwjynrtvllunelpkargfrkltadhzhggdmdtzordxrlxegknsqwmyqmpndpjtiwoutoxvgmxomhcjursxqzsoipvecltqjgurzhgsahpgrvshqddlqivbfiwcvrxpmneuwmpepyswrktflewfgfbtghjcvzfomsbozadzxzkmyzjsroftglrpmxzjnyekkiplfmuzkabmvdwurhuwnywqlxfzjzgsfsshbmszxxnxbotgryafvsyksaxvcxqbveuvqmutauqtcrqwnczzhrhgsjbxhnrpgxauqxtaouasklqxhndpsvrfcigpkjqgwyisaqzzcviqibbuzljshpbwgfgkjdcbsygptdebhyrdkmnibhedccpkoyfbgjbokdrxocfavwrqxrdrzfarhidwxcvtiqlmkecrhmvrbswyqsllxieztqppouuvxjuglyajhvypjtwegokegkmehefzdegorebhqfcnigvwceppgdslddiboztptjbnpkabbrftvofxpkzlowayjxqhhlhjanistxywkdwzsrlbktoteanrgysfszktfbwhzpbnafiywpifooqfyymcwreukinwtugxknlxvvsvhodciwgilhvipxycrbfljaoxkrivopksqrbpcwrhapzakhwceritvrmxvamlwfpnabyiesrveexiawsrxcqwprjebxtqoxaipuifnhqreuackqxbsdkrhlhigvttiwhecvkydzdglbtedvapgvrgrwrdjtbtzagpipnxrgbbhqpwtxdeisqzyhkpbfjuwiouezeqptiuqiupfqixbvarcuxauuteuzuaooxloihozntdbekmpjxelxgvheawrmpypbtyvhgzrwzgcgnixwblmccbbarxkhacoqmvkhaweylgrwdwncxtcjbckgyyazmhvxvgvqxegsbcccukuqhhbkvfhjlkpkcalkipehbsyobegwzfbpzekcojczrwetfficgpqyywfulsfkbschsxbgjzzesegzethrulciarlmigwiilrwehrrjrugxweqpuzuoribobjnaopkqggzkssjvqboaveqsucxxjavquczyvlqtvitwomlsufzjdkqrhpksyyvqgdcjxqxdgykuahsjbcjbpeuvjaksjmzslzcggwzxgkeyuhqmaztspmjijrzenidragcgitxqfbzikmtkymykmyghpczanqaljwpbmiecfefxhunwprekwbzvyytqltstohdwnoayfhrqkdkynuxbykldbdkebewfekpwydjxazqhtvtmradfueucvpbgpaofimpzlpovrsycefdjtcwkzjqyulvhyqecqnfrnjursztbkjshbxmdfqtsfxnyayuewobxdvgrweqxbzaaexnlekreqpchlaxabammpbnutcrnwqjfgvpxnqekfwfzdmmmgjwizrcljkqqdngxrqkysubkvkloehtlqsoahzejesemfskjnaabvivdzaesjcwcgoqpdkxzeadimurfibudankcqojhcmmarllxrbyfsvbxczujwalgnuadqyqmuymyyletojbwonjckavsehygtgfohpblimgxjksyibjyneezguuocezdrcxrxeoakrdwjofzyibdyurwpnvxcyclevjzziyfxsrbnrilrxhppymsbpfyydreefbjebqcplvquvcpnjsiazvtbbuxfgbzpzcumsdkhiquzorjsrdtywjezkgrzwmnucfzwwxubasemcwrlowrwwrrdezijifnihociusgtkkesqisqogakbuxrojteawxgwrjhwwugxdnohrocgihpydouauyyfakcxltvnjiiytiifrfbfgaeytzpsxqumrrmbpxkxxmrhoyzlclzokubjijwqfglmynvyvavnpmhnfhajuqksfvdibmuesjgizjxfrppsnijrqgjwymsqcqwzopolwujhictusjcqkxonxudlokicggqzngvdrwnvjkmctmmkqflzrihwweqomedtvthoyirbbvbmzqjjxgybkeghrgcuknpypexjphxplskotclposgcrqtucqxmtfymevwogaainbozfkrqdsufwydnnwtfshzgempbhtqtyqbvbijxorhkyriktysftjbjfwnwsbhbxsnbgwftkfqeqotysktttcwcvkiqhzsxbbczzqmuehybnnsryfjpbjeugbijoxusmfpmslfyqmfflmzemmymlvjjgnggrrnhpvcfadczffrkxkhjslazutdbhlyjorlmxvemyovvdxgudmtekxmlfdjphymzozcjdgsjfdvyvvwdqcbyjjbmbhgsdbspfbtqeoccbsthbpiiawxzcryyctlwakzfkblzpcjcprdgqzynlofvjowyickkgiclfytnnvamcenmykveovsjtzsqhpkhfcsdsgamgrzdjfhjebjzwptdctthyurldiuhmvkrkoqdkgcmncvdoeodkrsmrsaxvigvjwgbcaluxugjglinksmzmehkueewhmiiyemetbroygvjihzesfhonxsbbripltetlhavluabtawvwmafdnaurhtyhasdoblsjdixbklbpkktonkyaighnxtzmzbocgqpakqtjqgllopnlhjwvdasjiicucggmvuezpqlcpmgtfrierngeyvfixitibypkyegpfcvlmvioscjkifiezyyfdugjuwhqpnhejmsngrgqjdzqzbecahaubtevlrahlyyoperzgwvxvlvcuqikqkauhohgkalnbpkoziditeethfjgqmcrpwmpmponqfmybgbiynltwqjriyurfbrjdcyodergovzzclggplylbtcaczzjdoltqnceeixhauzmiucrqlpfyzcqgabmgiunytyflpqqqklnyiyiglbugnsfpeaypgksenpybsydlffhbgrvfugzbypedaqqosbcroglcxdhdjjgbkjnxpxfptyekvkjdebnzpzdyalgoeltjiyslqasltvkemsvdouzyqfwaoiyowsdttlmviqwibpajprqkiiqtuwjvfzfamjxnysqzcsypmtouiqrpkkjvwvnzzvlhzmgebyfhyrastklvtqixevkqeeqhwbixzxmrpkqhhobnrxkpdfkbszulzodjuxllodvfqwuvdwsqwazcgewekodarzjoolhduzebbcnpcbzjileoguojmugwsbkcjmmwaljtgwgtxthklhvamriutjkkhuubgqovxsnrlsmecgjulauzbxmeyjbjkgkxgtsawijgebdywsuyyfoztrtgxyqtlzcpqfaigdzzqqlaqdbjhaquycqewwvizzanbkscjbfvahzfkxraxtmjjqqjgqraxbqooohhzrynongnexigcddjddjmzmkwatidobckdpuodqulrzyvzdladwtkdrcggfmmqczkepljbhxnkwwgvgabzizgbbkzkzupytequzznkbjtqdqdyhvtjmaydkokyqhtcyzaiwfmgbqjqlaajsramuckwkcusnrpwrwdcowdssewzvzjsdjyiqphcmkuyoawnmeostrwgtkayrikjjlqqezhdjnqvecybfuumgalmlhtpuntwxozyeusxdhyyuashhmcegxfidxujgeztepavlyzvqdjwweamyeiitrsimvlbgbuoadhfgjozyxsksnplvzuffckkichkzyxhhvovpgpzbrwgkhvaabraffvpkwjrtmuzqqyggnxopkomagsmdwikypcfezuocmstjjyhbwbwiddoypxwfrdkodiuoogezcbwofuviyyfavsgevovovxdzyrwgqjlxsrqxotkprcpvtoizbxmxzdbtwplbkzcwwsrejqnnhispvyjmemkifkoqrblusxnigdhcrhtzudelzrijjpblcsrxgiixkunsfhgwvkbnhwbgbihhgvnriescelllgwmdvtcdbdwiqlrjfyrxusifmqkalqjzgizahjdifstlhtmbgmwkmxipkbjkqdpywqjlyhkvyxmmaxchzgjeoyaulvruafezywjtvpqzijhnwalqnqimxkkmskjkscriqlbvnnyptfmtbonbahpgcqfkoawepwbbuoqijfhbjnoeafnfndkjdyljucivoyhbeljsczgamkbgdlcpyxavznkgfqjfrrkhjxoahyrqyrzaiarglrhmwodxztnusgvkdkbapfttnroqsdeqsgtcgzygeegwauewebnpfepmlfnbtnmqlelrbdbsfflvvvffhahvkgsqtqzypycssvxngvlbfujtzuravnirwqgyrjqersajlfeadboixbwmrjhsncvemjoqztrsybdkdspkfyehwnxdxnsvkrknehohrfnaosaazxgaceftgavjskrcqzxzlzfszkibywtyvnllycapjmoavgrheepwpfwudvymwyycqutpiywcqstewvotvnblalcziwndiiubuasdvchtkcbxsekupgyldlafhcrncwxkurwrsxrwlfsjuqjvhaptkbdebevetovhbvgwtptjcwheitmbqbloskgigzastrpaiftkfqfyzezxendrkmexxnjozkiohiflngphsfeyklubfamjekzgvwijmcfrmeutkygcltbpticjdcwnvgisprbugvrdrlgtpjgotukshygfexehcimthlpcyaqgiaupgxccijbdqfuibkmduzxzikdzlzglvhyawfqhvvawcdwsqiivczgxdospqbgalxmzwaxztwdbelxajlxucffezlbquzhdjikiawduhxpfknqajrapdbwsktnpfxikfisxtjnokkcbqmjbepuojtfhomxnihszirttdxgzeljrgqmysisysqzczrsnekkkzkkgvqhrygqzjtopaplzylqmndcbbjfpycnuoykswlenpmcnuxezjuyckmhxpjbiacsfqsinqsqbjkzsalydkxvaivabvsrcpxhswfistngwhyndqfatpeiymvpppgmvqsvmtpihytitsobeqtjbkzgrpwbgjarjnhlumvfralmyuwrnhufiofpngqxjesmyedwusyfuybrjagovyzuikzuonevdksnxncoikrqfrhbghjuvhivbgaatmlzqzlohvudticakjzfkxnqzjkqebcjzjwbnznyibsnddidunyyhqjvbujnfhudlywwuznagrgiedupdowvflsefybqunxlsxpwurxlypxqkugdfcphmytzgacsheypgcxfpglfztvslnjvoueqwqjsgysunzybkcnhcnrhhwgsvhkjghybjakewzbksyvzgsvcjmhcwljdpvqlobkyjykajyizhigygalbcqrcjadlokamnymdmfpjndlmkzrhzuhbobqqlzymwvuluquhcrfywgrctmtbqxyrqffxxgxsebanpcxdyjywtnvccwzhttlhzffegybkmcewkrwxtoroyowffmhletdubphauxhokgtiqrlowigufmuiehuvcgjrqeuifmtdmotoocgqrthlmhhninnosbmgtlcaldmcfijsewczjvhtsingomsjqcdagysojjcjieggzevgfsbiwqkhzpozkiqtslfpblbuuvbzudlkribuyfysgzzwadpitstrjurmleuwbujaxeyhmsgkckgttqsefhzashpzydrvzfoxjcljazjhpapzfmeyfaywccqpqaxyacbhkhzwybiavwrewszmlpkjtnfzinmgyavvroxcnlpfcxcqjbhrlloxxsidqivcyripbwyegwehydlgazkedvxpepfgsukkslgnrpxiofagiyvqcacytrekqzpervtmqkpjcdprlqghcfntxjnlkkjgrpdiutsmttjptpzzkzuunqgwmsiigvryluctczsgydmpbrgmpyypqrkibltispmmciimcdaqiczhlnfththednvaizylkmelfhwtzawgikdmvsmuainofimfhtzqpaxraeimymxnaifqoilvzfsrwlxhdpbafyhkesbjhiitwkjtopkuwgpfwgvxrfygbevhppcjxwggopswqtdmubdumihtzrftsbongwcprjvofitummaejleysqghmvsjpmvkxnelqofdthbvkecnzgvvlosoobthftogyzvokeblfkkgirbjfqzjqhqxdllzrrngaxtrxxzxgesxvpkrfskwphhapjwxlmdbiqeewpeshyxjbmnsbmoljrafzyfkwvxhdbqdbxpnfomcpsnvrygsjbkwgvoxduojdsbbbuimixpkhzgloelxlgevxukpknfdbbczwukpgdzsuxscfixptkxzizsrbxnlicgamymxfnncgvuorjvscovuudtfkxgwtlxxaodsdiyymulzbrlwndhzuvbdiswjjzkclvsdylzuhiocjhqumfttochfcwdkyhwvqdnluujwflvrnutxfchhdicdwhbuajtsrxfphxhxrycqbjtmhkhyhygbewlyqwqropwgzsdvgghegwekktmfzlqezjtmgqcrlspvilanpnnotepvvurqzsffuyptxrzboobhymwufnhtcxjrjitqerponfzhevlfzrqnnqvjocwraptxooueeijouxavdbsfursnucvhspznehiedpnxwedittiqsjkvxqxrzvbgonxbhjnkxhulogmlqqlhftnfwvkgzwnbxdotqssfxciuliwohdttmesjsyhnxzagpkfqttkkboyoibdrzgjsflutyasqvcjloxwiwkspzxcxxjpzypcrfpqyauvkdcdashfkemqtxgwbwrmvcjqowsdqjmtoyifuncgjfvkhszgdwxfokfuphnzpsbrecdtyrsalutrpymowwtnjpyvebnupmytjqzuzcgvibkahhouzftgjxccqyqrvjrbkaqjdyqrqcnjuyscuetdaahkvdrcvdwyybftqjemsrfrqfpyktrkmzmowrziaiwgfomrjrkaaioqiitnwalvojfciktuesmlwskfnllhklfrwfvfvivjoterdhqyuwttjydiupbvpkkyoradldgngoqmvrasxvaqehcfaukebkwywnvypymviszsiazgciecwyxhuavlriwvwvarxuzthptqwajrzqchrdjvxmdmntwucmfyzubnfweqmodbiveukwdrxvtrmfiwxlsojsqwsllcqepvtdiuvtwwcislsucoygpophnhnjjiqspszsvynxjfzzjyvpgkoifppuivehwglskdtnptlztwklxfvhkamyidbwfaqdmperliyfsebkjltxpymjwjusbtupifijviibhijelqetkycooowqdvldnkokgyefngtikcmyghviqmtwqztrxgvviacryfeowyrurdybtfzseseidsvddfxvozkecybdrdowrusoakvgbgagrxbbxojowagrwpxkogtekdabfgyrrcrbuhpmlsenjnablrzsxwksmizrnnylkgmkzkrzilznehycnpmeuvxredmsshylsipzfjelorybknvrbgwnymlmienvytgcrsohmqcqoomisvepjdtqqsvrvkhvzagtwwvzurslxfzowpyjffdehiwsggnytxflhkkwbkmqusedcexefekoyulhzycxisleztbfyzeuzkecevdwuecgladepkzpazlggbutpgthxczuhxmyaflubisqohinubtqaatrtsmyuubgfbkoajlxvuyfftkxgrhyyajhhqpggurtexdzyqclbqrtropghnwmhozuodtoiyhuglclpdbmfjehtvdodnadfuoswpkpabhsytanosoqfnwrvaskgtwvbkjdjatczshbvddhfcnjcgobxnnyvgqexkpnapnrlnyxztlrrijyqefyzoqclhldafhpjjpumzagjmwhueiebboyvvfgiarbjtriunndulzigtgkbyxgvvdgjpbzczevlobumxzdtowwmlzqrhfpvymkyjblbylqylduwpwxccdbtlplqwgcjnmxvjligjrfuxuunppphpiadotqkzzynrmmwkhlkkwjrkdspncvfamqhkundcghttmghhrzeegegfjlruylggmqlzttdyzahpshwixwfotpapmqpnhkbjqwxaiweusnuehpoxvtztenlnuzcwwqnjtggetitjxxmejfvawtxbbptsjavciskpyrytqmrsscvgtzvnndlqtxqsaxtarwnzkmiwkjirelxyrrbyucvxvxosngsjhxxccnbgywsaowilznbhidmrpocarcnggcnvnromrrzrekjtlilhwouqqqqrfgmkmbvpacqewfjrqknqhbneushpdccthajoiuzrgpwocybcjwvazreixoxqpolchmuqclbikxmmixajsawucicjxnvmsplwwzilzewdtxyypbkhgrwfdpjpaggrygqgudkegwywxrfvcclbvlsiqqucrrwwnttmrmmvvwabyiyernwdwzuqrkkmqdsxrfpwidkeyqahpzixsxoehexjywvydrjgbqgkaklkmmjvcvjdsjwzuzcelphjpujqniwllbdzpqqbtkbuocavsbprwvuronlwpmuamrharifnbdpwevkfaxkdzpzatqpsopzwbrsqspcujsvupftfkyrlswasaxultoezkxwkumjtrhmimlazyubdckcbjlmoqafrbvqnfgayhdrlvoxceosfonpihtjprwvdlalnqjsphkwhmjccjotsvsqncjrvdfaqecqfmdndighintfurzonotwvdbwhyrpnizppwabiblhnkfkgckieaykqjrlfxugwdhyqshsxkjjjzusperaxzlvcpcmtymliqooxfupwpofgpcrldwqocwbuegfumgbvuipwjoashgaabaxcxpmqdjsfekutlttalgnixjceirzwmzcszuitxfphtgfplkxtdjfoaoyapyxjeotykeruchovoicqdbneefdrjpgmfwkzncobgmcoulvckxlbzswhshkgblrhglvqpteefqdmkvaclztfpppnmaxmzafzvzecgfidwubjmnqvrhqsmlqlfeqgykmeyhdcovdllopkkrofmsdirezrfakucroezvscxmlawvambcdbdbxcndvrrfbbghnmlpujdlfgwtzcxhxeqszuzwkuuigsvigwzulqumuscfrfadclqtobhdbodjanqotrprmiaddvvqijhmcbopstqgbuwbpasnyixfsfrymzrcxztuiddltmtaqxthtuswftctdkssupcbnrilmcgxjpxhviicoiyvbiffxeltqemyidascdkghlrlqxitrmfxminxfhsezourlbwrlfehsiegmirdtbcjyvycboved";
		System.out.println(maxNumberOfBalloons(s));
		System.out.println(maxBalloonConstantSpace(s));
	}
}
